spring:
  rabbitmq:
    host: 192.168.88.101 # rabbitmq 远程主机
    port: 5672 # rabbitmq 端口
    virtual-host: /hmall # 虚拟主机
    username: hmall # rabbitmq 用户
    password: 123456 # rabbitmq 密码
    listener:
      simple:
        prefetch: 1